[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "common_utils"
version = "0.1.0"
authors = []
description = "Common utilities for Project Taylor"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["common_utils"]
